config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :users, only: %w[edit update] do
    member do
      get :following, :followers
    end
  end
  get '/login', to: 'user_sessions#new' if Rails.env.test?
  post '/login', to: 'user_sessions#create' if Rails.env.test?
  get '/test-user1', to: 'user_sessions#test_user_1'
  get '/test-user2', to: 'user_sessions#test_user_2'
  delete '/logout', to: 'user_sessions#destroy'
  resources :posts, only: %w[index show new create]
  resources :joined_users, only: %w[create destroy]
  get '/now_join', to: 'joined_users#now_join'

  resources :game_starts, only: :show do
    member do
      get 'starting'
    end
  end

  namespace :api do
    resources :joins, only: :index
    resources :posts, only: :index
  end
  resources :relationships, only: %w[index create destroy]
  resources :blacklists, only: %w[create destroy]

  get '/terms', to: 'static_pages#terms'
  get '/explanation', to: 'static_pages#explanation'

  namespace :admin do
    root 'dashboards#top'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :posts, only: %w[index destroy]
    resources :users, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  include Encryptor

  has_many :posts, dependent: :destroy
  has_many :joined_user, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_blacklists, class_name: 'Blacklist', foreign_key: 'user_id', dependent: :destroy
  has_many :blacklisting, through: :active_blacklists, source: :target_user
  has_many :passive_blacklists, class_name: 'Blacklist', foreign_key: 'target_user_id', dependent: :destroy
  has_many :blacklisted, through: :passive_blacklists, source: :user

  validates :name, presence: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, uniqueness: true, allow_blank: true
  validates :game_name, length: { maximum: 12 }

  enum role: { general: 0, admin: 1 }

  def latest_post
    posts.last
  end

  def following_or_blacklisting?(target_user)
    blacklisting.include?(target_user) || following.include?(target_user)
  end

  def destroy_follow(target_user_id)
    relationship = Relationship.find_by(follower: id, followed: target_user_id)
    relationship.destroy!
  end

  def destroy_blacklist(target_user_id)
    blacklist = Blacklist.find_by(user_id: id, target_user_id: target_user_id)
    blacklist.destroy!
  end

  def set_access_token(token, secret)
    self.access_token = encrypt(token)
    self.access_token_secret = encrypt(secret)
  end

  def twitter_client
    @twitter_client ||= Twitter::REST::Client.new(
        consumer_key: Settings.twitter[:key],
        consumer_secret: Settings.twitter[:secret],
        access_token: decrypt(access_token),
        access_token_secret: decrypt(access_token_secret)
    )
  end

  def refresh_users_info(token, secret)
    set_access_token(token, secret) if access_token_updated?(token, secret) # twitter-developerからaccess_tokenをアップデートする人用の
    self.name = twitter_name
    # self.remote_avatar_url = twitter_avatar if avatar_changed?
    save if changed?
  end

  def twitter_name
    twitter_client.user.name
  end

  def twitter_avatar
    twitter_client.user.profile_image_url_https.to_s
  end

  # デプロイ時にS3を使用しているとエラーになる為、画像は更新しない処理に一旦変更
  # def avatar_changed?
  #   avatar.file.file.split('/').last != twitter_client.user.profile_image_url_https.to_s.split('/').last
  # end

  # 普通はfalse
  def access_token_updated?(token, secret)
    decrypt(access_token) != token || decrypt(access_token_secret) != secret
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  layout 'admin'

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %w[new create]
  before_action :set_user, only: %w[edit update]
  before_action :correct_users_page?, only: %w[edit update]

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(login_path, success: 'ユーザー登録が完了しました')
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def update
    @user.assign_attributes(user_params)
    if @user.game_name.present? && @user.save
      render :update
    else
      render :error
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :game_name, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_users_page?
    redirect_to root_path unless @user == current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='container'>
  <div id='current_user_name'>
    <%= image_tag current_user.avatar.to_s, id: 'user-edit-avatar' %><span><%= current_user.name %></span><span></span><span style="float: right;"><div><%= link_to 'アプリ説明', explanation_path, class: 'btn btn-info btn-lg' %></div><div><%= link_to 'ログアウト', logout_path, class: 'btn btn-danger btn-lg', id: 'logout-button', method: :delete %></div></span>
  </div>

  <div id='monst-name-form'>
    <span>モンストネーム：</span>
    <span id='current_user_game_name'>
      <% if @user.game_name.present? %>
        <span><%= @user.game_name %></span>
      <% else %>
        <h3 style="color: red">モンスト内のネームを登録してください</h3>
      <% end %>
    </span>
  </div>

  <div id='game-name-update-form'>
    <%= form_with model: @user, url: user_path(@user) do |form| %>
      <div id='game_name_error_message' style='color: red'></div>
      <div id='update_user_info'>
        <%= form.label :game_name %>
        <%= form.text_field :game_name, class: 'form-control' %>
      </div>
      <%= form.submit '更新する', class: 'btn btn-primary', id: 'user-update-button' %>
    <% end %>
  </div>

  <div id='following_blacklisting_button'>
    <button id='current_user_following_button' class='btn btn-info btn-lg' onclick='changeToFollowingList()'>フォローリスト</button>
    <button id='current_user_blacklisting_button' class='btn btn-danger btn-lg' onclick='changeToBlacklistingList()'>ブロックリスト</button>
  </div>

  <div id='following_or_blacklisting_list'>
    <div id='current_user_following_list'>
      <h3>フォローリスト</h3>
      <div id='following-users'>
        <% if @user.following.present? %>
          <%= render partial: 'shared/following_user', collection: @user.following, as: :following_user %>
        <% else %>
          <p>フォローしているユーザーはいません</p>
        <% end %>
      </div>
    </div>

    <div id='current_user_blacklisting_list'>
      <h3>ブロックリスト</h3>
      <div id='blacklisting-users'>
      <% if @user.blacklisting.present? %>
        <%= render partial: 'shared/blacklisting_user', collection: @user.blacklisting, as: :blacklisting_user %>
      <% else %>
        <p>ブロックしているユーザーはいません</p>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/error.js.erb
$('#game_name_error_message')[0].textContent = '12文字以内で入力してください'

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/update.js.erb
$('#game_name_error_message')[0].textContent = ''
$("#current_user_game_name")[0].textContent = "<%= @user.game_name %>"