config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :users, only: %w[edit update] do
    member do
      get :following, :followers
    end
  end
  get '/login', to: 'user_sessions#new' if Rails.env.test?
  post '/login', to: 'user_sessions#create' if Rails.env.test?
  get '/test-user1', to: 'user_sessions#test_user_1'
  get '/test-user2', to: 'user_sessions#test_user_2'
  delete '/logout', to: 'user_sessions#destroy'
  resources :posts, only: %w[index show new create]
  resources :joined_users, only: %w[create destroy]
  get '/now_join', to: 'joined_users#now_join'

  resources :game_starts, only: :show do
    member do
      get 'starting'
    end
  end

  namespace :api do
    resources :joins, only: :index
    resources :posts, only: :index
  end
  resources :relationships, only: %w[index create destroy]
  resources :blacklists, only: %w[create destroy]

  get '/terms', to: 'static_pages#terms'
  get '/explanation', to: 'static_pages#explanation'

  namespace :admin do
    root 'dashboards#top'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :posts, only: %w[index destroy]
    resources :users, only: :index
  end
end

app/views/shared/_block.html.erb
<%= link_to 'ブロックする', blacklists_path(block_user_id), class: 'btn btn-primary btn-lg', method: :post, remote: true %>

app/views/shared/_description_set_info.html.erb
<div class='input-character-info'>
  <button type='button' onclick="setDescriptionValue(this)" class="<%= count %> recruit-info-customize btn btn-danger">何でもOK</button>
  <button type='button' onclick="setDescriptionValue(this)" class="<%= count %> recruit-info-customize btn btn-danger">運極</button>
  <button type='button' onclick="setDescriptionValue(this)" class="<%= count %> recruit-info-customize btn btn-danger">超絶運極</button>
  <button type='button' onclick="setDescriptionValue(this)" class="<%= count %> recruit-info-customize btn btn-danger">実厳選</button>
  <button type='button' onclick="setDescriptionValue(this)" class="<%= count %> recruit-info-customize btn btn-danger">紋章厳選</button>
</div>

app/views/shared/_follow.html.erb
<%= link_to 'お気に入りする', relationships_path(follow_user_id), class: 'btn btn-primary btn-lg', method: :post, remote: true %>

app/views/shared/_following_or_blocking.html.erb
<% if current_user.following.include?(target_user) %>
  <%= render partial: 'shared/unfollow', locals: {follow_user_id: target_user} %>
<% else %>
  <%= render partial: 'shared/follow', locals: {follow_user_id: target_user} %>
<% end %>
<% if current_user.blacklisting.include?(target_user) %>
  <%= render partial: 'shared/unblock', locals: { block_user_id: target_user } %>
<% else %>
  <%= render partial: 'shared/block', locals: { block_user_id: target_user } %>
<% end %>

app/views/shared/_following_user.html.erb
<div class='following-user'>
  <span><%= following_user.name %></span>
  <span class='unfollow-button'><%= render partial: 'shared/unfollow', locals: {follow_user_id: following_user} %></span>
</div>

app/views/shared/_header.html.erb
<header>
  <div id='header-logo-and-link'>
    <%= link_to (image_tag 'logo.png', alt: 'ページタイトル画像', id: 'page-image'), root_path %>
    <%= link_to edit_user_path(current_user), id: 'header-user-profile' do %>
      <%= image_tag current_user.avatar.to_s, alt: 'ユーザープロフィール画像', id: 'header-user-avatar' %>
      <span id='header-user-name'><%= current_user.name[0, 8] %></span>
    <% end %>
  </div>
  <div id='header-logged-in-links'>
    <div id='header-image-links'>
      <%= link_to image_tag('posts_index.png'), posts_path, class: 'header-image-link', id: 'index-image-link' %>
      <%= link_to image_tag('recruit.png'), new_post_path, class: 'header-image-link', id: 'recruit-image-link' %>
      <%= link_to image_tag('recruiting_or_joining.png'), now_join_path, class: 'header-image-link', id: 'now-image-link' %>
      <%= link_to image_tag('request.png'), relationships_path, class: 'header-image-link', id: 'request-image-link' %>
    </div>
  </div>
</header>

app/views/shared/_index_recruiting_position.html.erb
<div class='index-recruit-info'>
  <p class='index-recruit-ch-desc'>モンスター: <%= recruit.character %></p>
  <p class='index-recruit-ch-desc'>詳細: <%= recruit.description %></p>
</div>

app/views/shared/_join_recruiting_position.html.erb
<%= link_to '参加する', joined_users_path(id: recruiting_position.id), class: 'btn btn-primary btn-lg', local: true, method: :post %>

app/views/shared/_not_logged_in_header.html.erb
<header>
  <div id='header-logo-and-link'>
    <%= link_to (image_tag 'logo.png', alt: 'ページタイトル画像', id: 'page-image'), root_path %>
    <%= link_to auth_at_provider_path(provider: :twitter), id: 'header-login-link' do %>
      <i class="fab fa-twitter fa-3x"></i>
      <span id='header-login-name'>ログイン</span>
    <% end %>
  </div>
  </div>
  <div class="container">
    <h3>採用担当者様へ：<%= link_to '使い方説明', explanation_path, class: 'btn btn-primary btn-lg' %></h3>
    <p>テストユーザー１ログイン：<%= link_to "テストユーザー１", test_user1_path, class: 'btn btn-primary btn-lg' %></p>
    <p>テストユーザー２ログイン：<%= link_to "テストユーザー２", test_user2_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
  <div id='not-logged-in-explanation'>
    <div id='page-explanation'>
      <h2>Twitterユーザー同士でモンストマルチが出来ます！！！</h2>
      <p>右上からツイッターアカウントでログイン</p>
    </div>
    <div id='page-explanation-button'>
      <%= link_to '使い方説明', explanation_path, class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
</header>

app/views/shared/_post.html.erb
<%= link_to post_path(post) do %>
  <div class='post-card'>
    <div class='post-user'>
      <%= image_tag post.user.avatar.to_s, alt: '投稿ユーザーの画像', class: 'index-user-avatar' %>
      <span class='index-user-name'><%= post.user.name[0, 18] %></span>
    </div>
    <p class='index-quest-name'><%= post.quest_name[0, 20] %></p>
    <div class='index-recruiting-positions'>
      <%= render partial: 'shared/index_recruiting_position', collection: post.recruiting_positions, as: :recruit %>
    </div>
  </div>
<% end %>

app/views/shared/_recruiting_position.html.erb
<div class='recruiting_position_style_start'>
  <div class='recruiting-info'>
    <div>
      <span>キャラクター：</span>
      <% if recruiting_position.character.present? %>
        <span><%= recruiting_position.character %></span>
      <% else %>
        <span>誰でもOK</span>
      <% end %>
    </div>

    <div>
      <span>ステータス：</span>
      <% if recruiting_position.description.present? %>
        <span><%= recruiting_position.description %></span>
      <% else %>
        <span>指定無し</span>
      <% end %>
    </div>
  </div>

  <div id="recruiting-position-style-<%= recruiting_position.id %>">
    <% unless current_user.id == recruiting_position.post.user_id %>
      <% if recruiting_position.joined_user.present? && current_user.id == recruiting_position.joined_user.user_id %>
        <%= render partial: 'shared/unjoin_recruiting_position', locals: {recruiting_position: recruiting_position} %>
      <% else %>
        <%= render partial: 'shared/join_recruiting_position', locals: {recruiting_position: recruiting_position} %>
      <% end %>
    <% end %>
  </div>

  <div class='joining-user'>
    <p class='joining-user-label'>参加者</p>
    <div class='user-twitter-name'>
      <span>ツイッターネーム：</span><span id="recruiting-position-name-<%= recruiting_position.id %>"></span>
    </div>
    <div class='user-monst-name'>
      <span>モンストネーム：</span><span id="recruiting-position-monst-name-<%= recruiting_position.id %>"></span>
    </div>
  </div>

  <% if current_user.id != recruiting_position.post.user_id %>
    <%= link_to "", '#', id: "game-start-#{ recruiting_position.id }", class: 'btn btn-danger btn-lg game-start-button' %>
  <% end %>
</div>

app/views/shared/_unblock.html.erb
<%= link_to 'ブロック解除', blacklist_path(block_user_id), class: 'btn btn-danger btn-lg', method: :delete, remote: true %>

app/views/shared/_unfollow.html.erb
<%= link_to 'お気に入り解除', relationship_path(follow_user_id), class: 'btn btn-danger btn-lg', method: :delete, remote: true %>

app/views/shared/_unjoin_recruiting_position.html.erb
<%= link_to '参加取り消し', joined_user_path(id: recruiting_position.id), class: 'btn btn-danger btn-lg', local: true, method: :delete %>