config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :users, only: %w[edit update] do
    member do
      get :following, :followers
    end
  end
  get '/login', to: 'user_sessions#new' if Rails.env.test?
  post '/login', to: 'user_sessions#create' if Rails.env.test?
  get '/test-user1', to: 'user_sessions#test_user_1'
  get '/test-user2', to: 'user_sessions#test_user_2'
  delete '/logout', to: 'user_sessions#destroy'
  resources :posts, only: %w[index show new create]
  resources :joined_users, only: %w[create destroy]
  get '/now_join', to: 'joined_users#now_join'

  resources :game_starts, only: :show do
    member do
      get 'starting'
    end
  end

  namespace :api do
    resources :joins, only: :index
    resources :posts, only: :index
  end
  resources :relationships, only: %w[index create destroy]
  resources :blacklists, only: %w[create destroy]

  get '/terms', to: 'static_pages#terms'
  get '/explanation', to: 'static_pages#explanation'

  namespace :admin do
    root 'dashboards#top'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :posts, only: %w[index destroy]
    resources :users, only: :index
  end
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  layout 'admin_login'
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :require_admin_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to admin_root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, danger: 'ログアウトしました'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %w[new create test_user_1 test_user_2]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end

  def test_user_1
    @user = login(Rails.application.credentials.test_user[:test_user_1][:email], Rails.application.credentials.test_user[:test_user_1][:password])
    redirect_to root_path, success: 'テストユーザー１でログインしました'
  end

  def test_user_2
    @user = login(Rails.application.credentials.test_user[:test_user_2][:email], Rails.application.credentials.test_user[:test_user_2][:password])
    redirect_to root_path, success: 'テストユーザー２でログインしました'
  end
end

app/helpers/admin/user_sessions_helper.rb
module Admin::UserSessionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <h1>ログイン</h1>
  <%= form_with url: login_path, local: true do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'ログイン', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%#= link_to 'Login with Twitter', auth_at_provider_path(provider: :twitter) %>
  <%= link_to auth_at_provider_path(provider: :twitter), id: 'session-login-link' do %>
    <i class="fab fa-twitter"></i>
    <span>ログイン</span>
  <% end %>
<!--  <div class='text-center'>-->
    <%#= link_to '登録ページへ', new_user_path %>
<!--  </div>-->
</div>